#!/usr/bin/env python3
# Copyright (c) Kyutai, all rights reserved.
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.
"""Generate shell scripts for distributed Phase 2 processing.

Creates individual shell scripts for each GPU machine to run Phase 2
word-level alignment using NeMo Forced Aligner (NFA).

Example usage:
    # Generate 8 scripts for 8 GPU machines
    python generate_phase2_scripts.py --total-machines 8

    # Generate with specific output directory
    python generate_phase2_scripts.py --total-machines 8 --output-dir ./scripts/phase2

    # Generate with custom Python path
    python generate_phase2_scripts.py --total-machines 8 --python-path /usr/bin/python3
"""

import argparse
import os
from pathlib import Path


SCRIPT_TEMPLATE = '''#!/bin/bash
# Phase 2 processing script for Machine {machine_id} of {total_machines}
# Auto-generated by generate_phase2_scripts.py
#
# This script runs word-level alignment using NeMo Forced Aligner (NFA)
# on a single GPU machine as part of distributed processing.
#
# Usage:
#   ./run_phase2_machine_{machine_id:03d}.sh
#
# Prerequisites:
#   - CUDA-capable GPU with sufficient memory (40GB+ recommended)
#   - NeMo toolkit installed: pip install nemo_toolkit[asr]
#   - ctc-segmentation installed: pip install ctc-segmentation
#   - Phase 1 processing completed and manifest available

set -e  # Exit on error

# ============================================================
# Configuration
# ============================================================
MACHINE_ID={machine_id}
TOTAL_MACHINES={total_machines}
GPU_ID=${{GPU_ID:-{gpu_id}}}  # Can override with GPU_ID env variable

# Paths
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
PYTHON="{python_path}"

# NFA Model (Korean CTC)
NFA_MODEL="{nfa_model}"

# ============================================================
# Environment Setup
# ============================================================
export CUDA_VISIBLE_DEVICES=$GPU_ID
export PYTHONPATH="$PROJECT_ROOT:$PYTHONPATH"

# Reduce NeMo logging verbosity
export HYDRA_FULL_ERROR=1
export NEMO_LOG_LEVEL=WARNING

echo "============================================================"
echo "Phase 2: Word-Level Alignment with NFA"
echo "============================================================"
echo "Machine:     $((MACHINE_ID + 1))/$TOTAL_MACHINES"
echo "GPU ID:      $GPU_ID"
echo "NFA Model:   $NFA_MODEL"
echo "Project:     $PROJECT_ROOT"
echo "============================================================"
echo ""

# ============================================================
# Run Phase 2 Processing
# ============================================================
cd "$PROJECT_ROOT"

$PYTHON data_preparation/scripts/run_phase2.py \\
    --machine-id $MACHINE_ID \\
    --total-machines $TOTAL_MACHINES \\
    --gpu $GPU_ID \\
    --aligner nfa \\
    --nfa-model "$NFA_MODEL" \\
    --resume \\
    "$@"

echo ""
echo "============================================================"
echo "Machine $((MACHINE_ID + 1))/$TOTAL_MACHINES completed!"
echo "============================================================"
echo ""
echo "Next steps:"
echo "  1. Wait for all $TOTAL_MACHINES machines to complete"
echo "  2. Run: python data_preparation/scripts/merge_phase2_results.py --total-machines $TOTAL_MACHINES"
'''


def main():
    parser = argparse.ArgumentParser(
        description="Generate Phase 2 distributed processing scripts"
    )
    parser.add_argument(
        "--total-machines",
        type=int,
        default=8,
        help="Total number of GPU machines (default: 8)",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path(__file__).parent / "phase2_distributed",
        help="Output directory for generated scripts",
    )
    parser.add_argument(
        "--python-path",
        type=str,
        default="python",
        help="Python executable path",
    )
    parser.add_argument(
        "--nfa-model",
        type=str,
        default="SungBeom/stt_kr_conformer_ctc_medium",
        help="NFA model name or path",
    )
    parser.add_argument(
        "--gpu-mapping",
        type=str,
        default=None,
        help="GPU mapping (comma-separated, e.g., '0,1,2,3,4,5,6,7'). "
             "If not specified, each machine uses GPU 0.",
    )

    args = parser.parse_args()

    # Create output directory
    args.output_dir.mkdir(parents=True, exist_ok=True)

    # Parse GPU mapping
    if args.gpu_mapping:
        gpu_ids = [int(g) for g in args.gpu_mapping.split(",")]
        if len(gpu_ids) != args.total_machines:
            print(f"Warning: GPU mapping has {len(gpu_ids)} entries, "
                  f"but total machines is {args.total_machines}")
            # Pad or truncate
            while len(gpu_ids) < args.total_machines:
                gpu_ids.append(0)
            gpu_ids = gpu_ids[:args.total_machines]
    else:
        # Default: each machine uses GPU 0 (assuming each runs on separate node)
        gpu_ids = [0] * args.total_machines

    print(f"Generating {args.total_machines} Phase 2 scripts...")
    print(f"Output directory: {args.output_dir}")
    print(f"NFA Model: {args.nfa_model}")
    print(f"GPU mapping: {gpu_ids}")
    print("")

    generated = []

    for machine_id in range(args.total_machines):
        script_name = f"run_phase2_machine_{machine_id:03d}.sh"
        script_path = args.output_dir / script_name

        content = SCRIPT_TEMPLATE.format(
            machine_id=machine_id,
            total_machines=args.total_machines,
            gpu_id=gpu_ids[machine_id],
            python_path=args.python_path,
            nfa_model=args.nfa_model,
        )

        with open(script_path, "w") as f:
            f.write(content)

        # Make executable
        os.chmod(script_path, 0o755)

        generated.append(script_path)
        print(f"  Created: {script_path}")

    # Create a run_all.sh script
    run_all_path = args.output_dir / "run_all.sh"
    run_all_content = f'''#!/bin/bash
# Run all Phase 2 machines in parallel (for single multi-GPU node)
# Warning: This requires {args.total_machines} GPUs on a single machine

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "Starting all {args.total_machines} Phase 2 machines in parallel..."
echo "Each machine will use a different GPU."
echo ""

'''
    for machine_id in range(args.total_machines):
        run_all_content += f'GPU_ID={gpu_ids[machine_id]} "$SCRIPT_DIR/run_phase2_machine_{machine_id:03d}.sh" &\n'

    run_all_content += f'''
echo "Waiting for all machines to complete..."
wait

echo ""
echo "All {args.total_machines} machines completed!"
echo "Run: python data_preparation/scripts/merge_phase2_results.py --total-machines {args.total_machines}"
'''

    with open(run_all_path, "w") as f:
        f.write(run_all_content)
    os.chmod(run_all_path, 0o755)
    print(f"  Created: {run_all_path}")

    # Create a SLURM job array script
    slurm_path = args.output_dir / "submit_slurm.sh"
    slurm_content = f'''#!/bin/bash
#SBATCH --job-name=phase2_nfa
#SBATCH --array=0-{args.total_machines - 1}
#SBATCH --nodes=1
#SBATCH --gpus-per-node=1
#SBATCH --mem=64G
#SBATCH --time=48:00:00
#SBATCH --output=logs/phase2_%a.log
#SBATCH --error=logs/phase2_%a.err

# SLURM job array script for Phase 2 distributed processing
# Submit with: sbatch submit_slurm.sh

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "Starting Phase 2 Machine $SLURM_ARRAY_TASK_ID of {args.total_machines}"

# Run the corresponding machine script
"$SCRIPT_DIR/run_phase2_machine_$(printf "%03d" $SLURM_ARRAY_TASK_ID).sh"
'''

    with open(slurm_path, "w") as f:
        f.write(slurm_content)
    os.chmod(slurm_path, 0o755)
    print(f"  Created: {slurm_path}")

    print("")
    print("=" * 60)
    print("Generated Scripts Summary")
    print("=" * 60)
    print(f"Total scripts: {len(generated) + 2}")
    print(f"Location: {args.output_dir}")
    print("")
    print("Usage options:")
    print("")
    print("1. Run individual machines manually:")
    print(f"   cd {args.output_dir}")
    print("   ./run_phase2_machine_000.sh  # On GPU machine 0")
    print("   ./run_phase2_machine_001.sh  # On GPU machine 1")
    print("   ...")
    print("")
    print("2. Run all machines on single multi-GPU node:")
    print(f"   cd {args.output_dir}")
    print("   ./run_all.sh")
    print("")
    print("3. Submit as SLURM job array:")
    print(f"   cd {args.output_dir}")
    print("   mkdir -p logs")
    print("   sbatch submit_slurm.sh")
    print("")
    print("After all machines complete, merge results:")
    print(f"   python data_preparation/scripts/merge_phase2_results.py --total-machines {args.total_machines}")
    print("")


if __name__ == "__main__":
    main()
